language: cpp

git:
  depth: 1

os:
  - linux

branches:
  only:
    - master
    - new_api
    - devel

compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: bionic
      env:
        - BUILD="qmake" GMIC_HOST="all"
    - os: linux
      dist: focal
      env:
        - BUILD="qmake" GMIC_HOST="all"
    - os: linux
      dist: bionic
      env:
        - BUILD="cmake" GMIC_HOST="none"
    - os: linux
      dist: bionic
      env:
        - BUILD="cmake" GMIC_HOST="gimp"
    - os: linux
      dist: bionic
      env:
        - BUILD="cmake" GMIC_HOST="krita"
  fast_finish: true

before_install:
  - date -u
  - uname -a
  - git clone --depth=1 https://github.com/dtschump/gmic.git gmic-clone
  - make -C gmic-clone/src CImg.h gmic_stdlib.h
  - if [ -z "$TRAVIS_OS_NAME" -o "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get update;
    fi;

install:
  - if [ -z "$TRAVIS_OS_NAME" -o "$TRAVIS_OS_NAME" = "linux" ]; then
       sudo apt-get install --allow-unauthenticated gdb libfftw3-dev zlib1g-dev libcurl4-openssl-dev libx11-dev libgimp2.0 libgegl-dev libgimp2.0-dev qt5-default qt5-qmake qtbase5-dev qttools5-dev qttools5-dev-tools;
    fi;

script:
  - g++ --version
  - if [ -z "$TRAVIS_OS_NAME" -o "$TRAVIS_OS_NAME" = "linux" ]; then
       travis_wait 45 ./scripts/travis_build_${BUILD}.sh;
    fi;
